# Generated by Django 6.0.4 on 2026-04-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='procent',
            new_name='percent',
        ),
    ]
